homepage:
    pattern:  /
    defaults: { _controller: PDSStoryBundle:Story:index}

login:
    pattern:  /login
    defaults: { _controller: PDSUserBundle:User:login}

login_check:
    pattern:  /login_check

signup:
    pattern:  /signup
    defaults: { _controller: PDSUserBundle:User:signup}

logout:
    pattern:  /logout

PDSUserBundle:
    resource: "@PDSUserBundle/Controller/"
    type:     annotation
    prefix:   /

PDSStoryBundle:
    resource: "@PDSStoryBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal


_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

#ToxSatelliteBundle:
#    resource: "@ToxSatelliteBundle/Controller/"
#    type:     annotation
#    prefix:   /
#
#ToxPlaceBundle:
#    resource: "@ToxPlaceBundle/Controller/"
#    type:     annotation
#    prefix:   /
#

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal