homepage:
    pattern:  /
    defaults: { _controller: PDSStoryBundle:Story:index}

login:
    pattern:  /login
    defaults: { _controller: PDSUserBundle:User:login}

login_check:
    pattern:  /login_check

signup:
    pattern:  /signup
    defaults: { _controller: PDSUserBundle:User:signup}

logout:
    pattern:  /logout

PDSUserBundle:
    resource: "@PDSUserBundle/Controller/"
    type:     annotation
    prefix:   /

PDSStoryBundle:
    resource: "@PDSStoryBundle/Controller/"
    type:     annotation
    prefix:   /
