security:
    encoders:
        PDS\UserBundle\Entity\User:
            id: pds_encoder

    role_hierarchy:
        ROLE_MODERATOR:   ROLE_USER
        ROLE_CONTRIBUTOR: [ROLE_USER, ROLE_MODERATOR, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN:       [ROLE_USER,ROLE_MODERATOR,ROLE_CONTRIBUTOR,ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class: PDSUserBundle:User

    firewalls:
        data:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false



        users:
            anonymous: ~
            pattern:    ^/
            form_login:
              check_path: /login_check
              login_path: /login
              username_parameter: username
              password_parameter: password
            logout:
              path: /logout
              target: /


    access_control:
        - { path: ^/|(story/time/[0-9]+|story/location/[0-9]+|story/topic/[0-9]+|story/teller/[0-9]+|story/tag/.+|story/|story/[0-9]+/show|login_check|login|signup)$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/, roles: ROLE_USER}
