Comment:
  type: entity
  table: comment
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    message:
      type: text
      nullable: false
    created_at:
      type: datetime
      nullable: false
  manyToOne:
    Story:
      targetEntity: Story
      inversedBy: Comments
      joinColumns:
        story_id:
          referencedColumnName: id
    User:
      targetEntity: User
      inversedBy: Comments
      joinColumns:
        user_id:
          referencedColumnName: id
