PDS\StoryBundle\Entity\Comment:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    message:
      type: text
      nullable: false
    created_at:
      type: datetime
      nullable: false
  manyToOne:
    Story:
      targetEntity: PDS\StoryBundle\Entity\Story
      inversedBy: Comments
      joinColumns:
        story_id:
          referencedColumnName: id
    User:
      targetEntity: PDS\UserBundle\Entity\User
      inversedBy: Comments
      joinColumns:
        user_id:
          referencedColumnName: id
