PDS\StoryBundle\Entity\Country:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      nullable: false
  oneToMany:
    Storeis:
      targetEntity: PDS\StoryBundle\Entity\Story
      mappedBy: Country
    Users:
      targetEntity: PDS\UserBundle\Entity\User
      mappedBy: Country
