PDS\StoryBundle\Entity\Status:
  type: entity
  table: status
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      nullable: false
  oneToMany:
    Stories:
      targetEntity: PDS\StoryBundle\Entity\Story
      mappedBy: Status
