PDS\StoryBundle\Entity\Story:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    title:
      type: string
      nullable: false
    body:
      type: text
      nullable: false
    created_at:
      type: datetime
      nullable: false
    date:
      type: date
      nullable: true
  oneToMany:
    Votes:
      targetEntity: PDS\StoryBundle\Entity\Vote
      mappedBy: Story
    Comments:
      targetEntity: PDS\StoryBundle\Entity\Comment
      mappedBy: Story
  manyToOne:
    User:
      targetEntity: PDS\UserBundle\Entity\User
      inversedBy: Stories
      joinColumns:
        user_id:
          referencedColumnName: id
    Country:
      targetEntity: PDS\StoryBundle\Entity\Country
      inversedBy: Storeis
      joinColumns:
        country_id:
          referencedColumnName: id
    Time:
      targetEntity: PDS\StoryBundle\Entity\Time
      inversedBy: Stories
      joinColumns:
        time_id:
          referencedColumnName: id
  manyToMany:
    Topics:
      targetEntity: Topic
      inversedBy: Stories
      joinTable:
        name: StoryTopic
        joinColumns:
          story_id:
            referencedColumnName: id
        inverseJoinColumns:
          topic_id:
            referencedColumnName: id
