PDS\StoryBundle\Entity\Story:
  type: entity
  repositoryClass: PDS\StoryBundle\Entity\StoryRepository
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    title:
      type: string
      nullable: false
    meta:
      type: text
      nullable: false
    created_at:
      type: datetime
      nullable: false
    date:
      type: date
      nullable: true
    meta_place:
      type: text
      nullable: true
  oneToMany:
    Votes:
      targetEntity: PDS\StoryBundle\Entity\Vote
      mappedBy: Story
    Comments:
      targetEntity: PDS\StoryBundle\Entity\Comment
      mappedBy: Story
    Pages:
      targetEntity: PDS\StoryBundle\Entity\Page
      mappedBy: Story
  manyToOne:
    User:
      targetEntity: PDS\UserBundle\Entity\User
      inversedBy: Stories
      joinColumns:
        user_id:
          referencedColumnName: id
    Country:
      targetEntity: PDS\StoryBundle\Entity\Country
      inversedBy: Stories
      joinColumns:
        country_id:
          referencedColumnName: id
    Time:
      targetEntity: PDS\StoryBundle\Entity\Time
      inversedBy: Stories
      joinColumns:
        time_id:
          referencedColumnName: id
    Status:
      targetEntity: PDS\StoryBundle\Entity\Status
      inversedBy: Stories
      joinColumns:
        status_id:
          referencedColumnName: id
