PDS\StoryBundle\Entity\Tag:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
  oneToMany:
    tagging:
      targetEntity: PDS\StoryBundle\Entity\Tagging
      mappedBy: tag
