Tag:
  type: entity
  table: tag
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
  oneToMany:
    tagging:
      targetEntity: Tagging
      mappedBy: tag
