PDS\StoryBundle\Entity\Tagging:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
  manyToOne:
    tag:
      targetEntity: PDS\StoryBundle\Entity\Tag
      inversedBy: tagging
      joinColumns:
        tag_id:
          referencedColumnName: id
