Tagging:
  type: entity
  table: tagging
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
  manyToOne:
    tag:
      targetEntity: Tag
      inversedBy: tagging
      joinColumns:
        tag_id:
          referencedColumnName: id
