Time:
  type: entity
  table: time
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      nullable: false
  oneToMany:
    Stories:
      targetEntity: Story
      mappedBy: Time
