Vote:
  type: entity
  table: vote
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    value:
      type: integer
      nullable: false
  uniqueConstraints:
    unqiue_pair:
      columns: [user_id, story_id]
  manyToOne:
    Story:
      targetEntity: Story
      inversedBy: Votes
      joinColumns:
        story_id:
          referencedColumnName: id
    User:
      targetEntity: User
      inversedBy: Votes
      joinColumns:
        user_id:
          referencedColumnName: id
