Role:
  type: entity
  table: role
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      unique: true
      nullable: false
  manyToMany:
    Users:
      targetEntity: User
      mappedBy: Roles
